# Generated by Django 5.2.9 on 2025-12-07 16:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('email', models.EmailField(help_text='Primair e-mailadres voor inloggen en communicatie', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='e-mailadres')),
                ('first_name', models.CharField(blank=True, help_text='Voornaam van de gebruiker', max_length=150, verbose_name='voornaam')),
                ('last_name', models.CharField(blank=True, help_text='Achternaam van de gebruiker', max_length=150, verbose_name='achternaam')),
                ('phone_number', models.CharField(blank=True, help_text='Primair telefoonnummer', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Telefoonnummer moet in het formaat: '+31612345678'. Maximaal 15 cijfers.", regex='^\\+?1?\\d{9,15}$')], verbose_name='telefoonnummer')),
                ('is_active', models.BooleanField(default=True, help_text='Geeft aan of de gebruiker actief is. In plaats van accounts te verwijderen, zet deze op False.', verbose_name='actief')),
                ('is_staff', models.BooleanField(default=False, help_text='Geeft aan of de gebruiker kan inloggen op de admin site.', verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, help_text='Geeft aan of de gebruiker alle permissies heeft zonder ze expliciet toe te wijzen.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Datum wanneer de gebruiker zich registreerde', verbose_name='aanmelddatum')),
                ('last_login', models.DateTimeField(blank=True, help_text='Datum van de laatste succesvolle login', null=True, verbose_name='laatste login')),
                ('profile_picture', models.ImageField(blank=True, help_text='Optionele profielfoto', null=True, upload_to='profile_pictures/%Y/%m/%d/', verbose_name='profielafbeelding')),
                ('job_title', models.CharField(blank=True, help_text='Functietitel binnen het bedrijf', max_length=100, verbose_name='functietitel')),
                ('department', models.CharField(blank=True, help_text='Afdeling waar de gebruiker werkt', max_length=100, verbose_name='afdeling')),
                ('language', models.CharField(choices=[('nl', 'Nederlands'), ('en', 'Engels'), ('de', 'Duits'), ('ar', 'Arabisch')], default='nl', help_text='Voorkeurstaal voor de interface', max_length=10, verbose_name='taalvoorkeur')),
                ('timezone', models.CharField(default='Europe/Amsterdam', help_text='Voorkeur tijdzone', max_length=50, verbose_name='tijdzone')),
                ('email_notifications', models.BooleanField(default=True, help_text='Of de gebruiker e-mail notificaties wil ontvangen', verbose_name='e-mail notificaties')),
                ('notes', models.TextField(blank=True, help_text='Interne notities over deze gebruiker', verbose_name='notities')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'gebruiker',
                'verbose_name_plural': 'gebruikers',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Beschrijving van de uitgevoerde actie', max_length=100, verbose_name='actie')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP adres van waar de actie werd uitgevoerd', null=True, verbose_name='IP adres')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device informatie', null=True, verbose_name='user agent')),
                ('details', models.JSONField(default=dict, help_text='Gedetailleerde informatie over de actie', verbose_name='details')),
                ('status', models.CharField(choices=[('success', 'Succes'), ('failed', 'Mislukt'), ('warning', 'Waarschuwing')], default='success', max_length=20, verbose_name='status')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='tijdstip')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='gebruiker')),
            ],
            options={
                'verbose_name': 'activiteitenlog',
                'verbose_name_plural': 'activiteitenlogs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_email', models.EmailField(blank=True, help_text='Optioneel secundair e-mailadres', max_length=254, null=True, verbose_name='secundair e-mailadres')),
                ('secondary_phone', models.CharField(blank=True, help_text='Optioneel secundair telefoonnummer', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Telefoonnummer moet in het formaat: '+31612345678'. Maximaal 15 cijfers.", regex='^\\+?1?\\d{9,15}$')], verbose_name='secundair telefoonnummer')),
                ('street', models.CharField(blank=True, help_text='Straatnaam en huisnummer', max_length=200, verbose_name='straat')),
                ('postal_code', models.CharField(blank=True, help_text='Postcode', max_length=10, verbose_name='postcode')),
                ('city', models.CharField(blank=True, help_text='Stad', max_length=100, verbose_name='stad')),
                ('country', models.CharField(default='Nederland', help_text='Land', max_length=100, verbose_name='land')),
                ('date_of_birth', models.DateField(blank=True, help_text='Geboortedatum', null=True, verbose_name='geboortedatum')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Man'), ('female', 'Vrouw'), ('other', 'Anders'), ('prefer_not_to_say', 'Zeg ik liever niet')], help_text='Geslacht', max_length=20, verbose_name='geslacht')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profiel URL', null=True, verbose_name='LinkedIn URL')),
                ('twitter_handle', models.CharField(blank=True, help_text='Twitter gebruikersnaam', max_length=50, null=True, verbose_name='Twitter handle')),
                ('employee_id', models.CharField(blank=True, help_text='Uniek medewerkersnummer', max_length=50, null=True, verbose_name='medewerker ID')),
                ('hire_date', models.DateField(blank=True, help_text='Datum van indiensttreding', null=True, verbose_name='in dienst vanaf')),
                ('theme', models.CharField(choices=[('light', 'Licht'), ('dark', 'Donker'), ('auto', 'Automatisch')], default='light', help_text='Interface thema voorkeur', max_length=20, verbose_name='thema')),
                ('notification_preferences', models.JSONField(default=dict, help_text='Gedetailleerde notificatie voorkeuren', verbose_name='notificatie voorkeuren')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='aangemaakt op')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='bijgewerkt op')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='gebruiker')),
            ],
            options={
                'verbose_name': 'gebruikersprofiel',
                'verbose_name_plural': 'gebruikersprofielen',
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='authenticat_email_486e08_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active'], name='authenticat_is_acti_0cde8a_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['date_joined'], name='authenticat_date_jo_e2032e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['last_login'], name='authenticat_last_lo_fbb915_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', 'timestamp'], name='authenticat_user_id_fef499_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['action', 'timestamp'], name='authenticat_action_253055_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['status', 'timestamp'], name='authenticat_status_888d57_idx'),
        ),
    ]
