# Generated by Django 5.2.9 on 2025-12-07 18:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
        ('projects', '0001_initial'),
        ('quotes', '__first__'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Naam van de tag', max_length=50, unique=True, verbose_name='naam')),
                ('slug', models.SlugField(help_text='URL-vriendelijke naam', max_length=60, unique=True, verbose_name='slug')),
                ('color', models.CharField(default='#3498db', help_text='Hex kleurcode voor visualisatie', max_length=7, verbose_name='kleur')),
                ('description', models.TextField(blank=True, help_text='Beschrijving van wanneer deze tag gebruikt wordt', verbose_name='beschrijving')),
                ('is_active', models.BooleanField(default=True, help_text='Of deze tag beschikbaar is voor gebruik', verbose_name='actief')),
            ],
            options={
                'verbose_name': 'order tag',
                'verbose_name_plural': 'order tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Beschrijvende naam van de bijlage', max_length=200, verbose_name='naam')),
                ('file', models.FileField(help_text='Het geüploade bestand', upload_to='order_attachments/%Y/%m/%d/', verbose_name='bestand')),
                ('file_type', models.CharField(blank=True, help_text='MIME type van het bestand', max_length=100, verbose_name='bestandstype')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Grootte in bytes', null=True, verbose_name='bestandsgrootte')),
                ('attachment_type', models.CharField(choices=[('invoice', 'Factuur'), ('delivery_note', 'Leveringsbon'), ('packing_list', 'Pakbon'), ('certificate', 'Certificaat'), ('warranty', 'Garantiebewijs'), ('photo', 'Foto'), ('other', 'Overig')], default='other', max_length=50, verbose_name='bijlage type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='geüpload op')),
                ('description', models.TextField(blank=True, help_text='Extra beschrijving van de bijlage', verbose_name='beschrijving')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_attachments', to=settings.AUTH_USER_MODEL, verbose_name='geüpload door')),
            ],
            options={
                'verbose_name': 'order bijlage',
                'verbose_name_plural': 'order bijlagen',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unieke identificatie voor dit object', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Datum en tijd wanneer dit object aangemaakt is', verbose_name='aangemaakt op')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Datum en tijd wanneer dit object voor het laatst bijgewerkt is', verbose_name='bijgewerkt op')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicatie of dit object zacht verwijderd is', verbose_name='verwijderd')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Datum en tijd wanneer dit object zacht verwijderd is', null=True, verbose_name='verwijderd op')),
                ('version', models.PositiveIntegerField(default=1, help_text='Versienummer voor optimistic locking', verbose_name='versie')),
                ('order_number', models.CharField(editable=False, help_text='Uniek ordernummer gegenereerd door het systeem', max_length=50, unique=True, verbose_name='ordernummer')),
                ('reference', models.CharField(blank=True, help_text='Interne referentie of klantreferentie', max_length=100, null=True, verbose_name='referentie')),
                ('status', models.CharField(choices=[('draft', 'Concept'), ('pending', 'In afwachting'), ('confirmed', 'Bevestigd'), ('processing', 'In verwerking'), ('ready_for_shipment', 'Gereed voor verzending'), ('shipped', 'Verzonden'), ('delivered', 'Afgeleverd'), ('partially_delivered', 'Gedeeltelijk afgeleverd'), ('cancelled', 'Geannuleerd'), ('refunded', 'Terugbetaald'), ('completed', 'Voltooid')], default='draft', help_text='Huidige status van de order', max_length=30, verbose_name='status')),
                ('priority', models.CharField(choices=[('low', 'Laag'), ('medium', 'Medium'), ('high', 'Hoog'), ('urgent', 'Urgent')], default='medium', help_text='Prioriteit voor verwerking', max_length=20, verbose_name='prioriteit')),
                ('currency', models.CharField(default='EUR', help_text='Valuta waarin de order is opgesteld (ISO 4217 code)', max_length=3, verbose_name='valuta')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, help_text='Wisselkoers t.o.v. basisvaluta', max_digits=10, verbose_name='wisselkoers')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=21.0, help_text='BTW percentage dat wordt toegepast', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='btw percentage')),
                ('tax_inclusive', models.BooleanField(default=True, help_text='Zijn de prijzen inclusief BTW?', verbose_name='btw inclusief')),
                ('payment_status', models.CharField(choices=[('pending', 'In afwachting'), ('partially_paid', 'Gedeeltelijk betaald'), ('paid', 'Betaald'), ('overdue', 'Achterstallig'), ('refunded', 'Terugbetaald'), ('failed', 'Mislukt')], default='pending', help_text='Huidige betaalstatus', max_length=20, verbose_name='betaalstatus')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bankoverschrijving'), ('credit_card', 'Creditcard'), ('debit_card', 'Debitcard'), ('paypal', 'PayPal'), ('ideal', 'iDEAL'), ('cash', 'Contant'), ('invoice', 'Factuur'), ('other', 'Overig')], default='invoice', help_text='Gebruikte betaalmethode', max_length=50, verbose_name='betaalmethode')),
                ('payment_terms', models.TextField(blank=True, help_text='Specifieke betalingsvoorwaarden voor deze order', verbose_name='betalingsvoorwaarden')),
                ('payment_due_date', models.DateField(blank=True, help_text='Datum waarop betaling vervalt', null=True, verbose_name='vervaldatum betaling')),
                ('delivery_date', models.DateTimeField(blank=True, help_text='Geplande leverdatum', null=True, verbose_name='leverdatum')),
                ('actual_delivery_date', models.DateTimeField(blank=True, help_text='Werkelijke leverdatum', null=True, verbose_name='werkelijke leverdatum')),
                ('shipping_method', models.CharField(blank=True, help_text='Gebruikte verzendmethode', max_length=100, verbose_name='verzendmethode')),
                ('tracking_number', models.CharField(blank=True, help_text='Trackingnummer voor verzending', max_length=100, null=True, verbose_name='trackingnummer')),
                ('shipping_costs', models.DecimalField(decimal_places=2, default=0, help_text='Kosten voor verzending', max_digits=10, verbose_name='verzendkosten')),
                ('internal_notes', models.TextField(blank=True, help_text='Interne notities voor het team', verbose_name='interne notities')),
                ('client_notes', models.TextField(blank=True, help_text='Notities voor de klant', verbose_name='klantnotities')),
                ('terms_conditions', models.TextField(blank=True, help_text='Algemene voorwaarden van toepassing', verbose_name='algemene voorwaarden')),
                ('delivery_instructions', models.TextField(blank=True, help_text='Speciale instructies voor levering', verbose_name='leveringsinstructies')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Datum/tijd wanneer de order is bevestigd', null=True, verbose_name='bevestigd op')),
                ('processing_started_at', models.DateTimeField(blank=True, help_text='Datum/tijd wanneer verwerking is gestart', null=True, verbose_name='verwerking gestart op')),
                ('shipped_at', models.DateTimeField(blank=True, help_text='Datum/tijd wanneer de order is verzonden', null=True, verbose_name='verzonden op')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Datum/tijd wanneer de order is afgeleverd', null=True, verbose_name='afgeleverd op')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Datum/tijd wanneer de order is geannuleerd', null=True, verbose_name='geannuleerd op')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Datum/tijd wanneer de order is voltooid', null=True, verbose_name='voltooid op')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Medewerker verantwoordelijk voor deze order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='toegewezen aan')),
                ('billing_address', models.ForeignKey(blank=True, help_text='Factuuradres voor deze order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='clients.address', verbose_name='factuuradres')),
                ('client', models.ForeignKey(help_text='Klant voor wie de order is', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.client', verbose_name='klant')),
                ('contact_person', models.ForeignKey(blank=True, help_text='Contactpersoon bij de klant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='clients.clientcontact', verbose_name='contactpersoon')),
                ('created_by', models.ForeignKey(blank=True, help_text='Gebruiker die dit object aangemaakt heeft', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='aangemaakt door')),
                ('delivery_address', models.ForeignKey(blank=True, help_text='Afleveradres voor deze order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='clients.address', verbose_name='afleveradres')),
                ('project', models.ForeignKey(blank=True, help_text='Project waartoe deze order behoort', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='projects.project', verbose_name='project')),
                ('quote', models.ForeignKey(blank=True, help_text='Offerte waarvan deze order is gemaakt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='quotes.quote', verbose_name='offerte')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Gebruiker die dit object voor het laatst bijgewerkt heeft', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='bijgewerkt door')),
                ('attachments', models.ManyToManyField(blank=True, help_text='Documenten en bijlagen bij de order', related_name='orders', to='orders.orderattachment', verbose_name='bijlagen')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags voor categorisatie en filtering', related_name='orders', to='orders.ordertag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Aangemaakt'), ('updated', 'Bijgewerkt'), ('status_changed', 'Status gewijzigd'), ('confirmed', 'Bevestigd'), ('processing_started', 'Verwerking gestart'), ('shipped', 'Verzonden'), ('delivered', 'Afgeleverd'), ('cancelled', 'Geannuleerd'), ('completed', 'Voltooid'), ('payment_received', 'Betaling ontvangen'), ('note_added', 'Notitie toegevoegd'), ('attachment_added', 'Bijlage toegevoegd')], max_length=50, verbose_name='actie')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='oude waarde')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='nieuwe waarde')),
                ('changed_fields', models.JSONField(default=list, help_text='Lijst van gewijzigde veldnamen', verbose_name='gewijzigde velden')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='gewijzigd op')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP adres')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='user agent')),
                ('notes', models.TextField(blank=True, help_text='Extra informatie over de wijziging', verbose_name='notities')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_changes', to=settings.AUTH_USER_MODEL, verbose_name='gewijzigd door')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'order geschiedenis',
                'verbose_name_plural': 'order geschiedenis',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(editable=False, help_text='Uniek betalingnummer', max_length=50, unique=True, verbose_name='betalingnummer')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Betaald bedrag', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='bedrag')),
                ('currency', models.CharField(default='EUR', help_text='Valuta van de betaling', max_length=3, verbose_name='valuta')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bankoverschrijving'), ('credit_card', 'Creditcard'), ('debit_card', 'Debitcard'), ('paypal', 'PayPal'), ('ideal', 'iDEAL'), ('cash', 'Contant'), ('other', 'Overig')], help_text='Gebruikte betaalmethode', max_length=50, verbose_name='betaalmethode')),
                ('status', models.CharField(choices=[('pending', 'In afwachting'), ('processing', 'In verwerking'), ('completed', 'Voltooid'), ('failed', 'Mislukt'), ('refunded', 'Terugbetaald'), ('cancelled', 'Geannuleerd')], default='pending', max_length=20, verbose_name='status')),
                ('transaction_id', models.CharField(blank=True, help_text='Transactie ID van de betalingsprovider', max_length=200, null=True, verbose_name='transactie ID')),
                ('payment_date', models.DateTimeField(help_text='Datum/tijd van de betaling', verbose_name='betaaldatum')),
                ('received_date', models.DateTimeField(blank=True, help_text='Datum/tijd wanneer betaling ontvangen is', null=True, verbose_name='ontvangstdatum')),
                ('payer_name', models.CharField(blank=True, help_text='Naam van de betaler', max_length=200, verbose_name='betalersnaam')),
                ('payer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='betalers e-mail')),
                ('notes', models.TextField(blank=True, help_text='Notities over deze betaling', verbose_name='notities')),
                ('receipt', models.FileField(blank=True, help_text='Scan of foto van de betalingsbewijs', null=True, upload_to='payment_receipts/%Y/%m/%d/', verbose_name='bon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='aangemaakt op')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='bijgewerkt op')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'betaling',
                'verbose_name_plural': 'betalingen',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(default=1, help_text='Volgnummer in de order', verbose_name='regelnummer')),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('service', 'Dienst'), ('material', 'Materiaal'), ('labor', 'Arbeid'), ('other', 'Overig')], default='product', help_text='Type van dit item', max_length=20, verbose_name='type item')),
                ('description', models.TextField(help_text='Gedetailleerde omschrijving van het item', verbose_name='omschrijving')),
                ('specification', models.TextField(blank=True, help_text='Technische specificaties of aanvullende informatie', verbose_name='specificatie')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, help_text='Aantal eenheden', max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='aantal')),
                ('unit', models.CharField(default='stuk', help_text='Eenheid (stuk, uur, meter, etc.)', max_length=20, verbose_name='eenheid')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Prijs per eenheid exclusief BTW', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='eenheidsprijs')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Kostprijs per eenheid (voor winstberekening)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='kostprijs')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Korting percentage op dit item', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='kortingspercentage')),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Specifiek BTW percentage voor dit item (laat leeg voor order default)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='btw percentage')),
                ('stock_location', models.CharField(blank=True, help_text='Locatie in het magazijn', max_length=100, verbose_name='voorraadlocatie')),
                ('batch_number', models.CharField(blank=True, help_text='Batchnummer (voor traceability)', max_length=100, null=True, verbose_name='batchnummer')),
                ('serial_number', models.CharField(blank=True, help_text='Serienummer (voor traceability)', max_length=100, null=True, verbose_name='serienummer')),
                ('is_delivered', models.BooleanField(default=False, help_text='Is dit item afgeleverd?', verbose_name='afgeleverd')),
                ('delivered_quantity', models.DecimalField(decimal_places=3, default=0, help_text='Aantal eenheden dat is afgeleverd', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='afgeleverd aantal')),
                ('delivery_date', models.DateTimeField(blank=True, help_text='Leverdatum voor dit specifieke item', null=True, verbose_name='leverdatum item')),
                ('notes', models.TextField(blank=True, help_text='Interne notities over dit item', verbose_name='notities')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='services.service', verbose_name='dienst')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
                'ordering': ['line_number'],
                'unique_together': {('order', 'line_number')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'created_at'], name='orders_orde_client__8a22e4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'priority'], name='orders_orde_status_b59646_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='orders_orde_payment_bc131d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_date'], name='orders_orde_deliver_e4274f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['assigned_to', 'status'], name='orders_orde_assigne_6abf64_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_date__gt', models.F('created_at'))), name='delivery_date_after_creation'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_number'], name='orders_paym_payment_00c7b5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='orders_paym_order_i_e3de73_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='orders_paym_payment_9e5ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='orders_paym_transac_29fb2b_idx'),
        ),
    ]
