# Generated by Django 5.2.9 on 2025-12-07 18:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Naam van de categorie', max_length=100, unique=True, verbose_name='naam')),
                ('slug', models.SlugField(help_text='URL-vriendelijke naam', max_length=110, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Beschrijving van de categorie', verbose_name='beschrijving')),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class (bijv. fa-building)', max_length=50, verbose_name='icoon')),
                ('color', models.CharField(default='#3498db', help_text='Hex kleurcode voor visualisatie', max_length=7, verbose_name='kleur')),
                ('is_active', models.BooleanField(default=True, help_text='Of deze categorie beschikbaar is voor gebruik', verbose_name='actief')),
            ],
            options={
                'verbose_name': 'project categorie',
                'verbose_name_plural': 'project categorieën',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Naam van de tag', max_length=50, unique=True, verbose_name='naam')),
                ('slug', models.SlugField(help_text='URL-vriendelijke naam', max_length=60, unique=True, verbose_name='slug')),
                ('color', models.CharField(default='#3498db', help_text='Hex kleurcode voor visualisatie', max_length=7, verbose_name='kleur')),
                ('description', models.TextField(blank=True, help_text='Beschrijving van wanneer deze tag gebruikt wordt', verbose_name='beschrijving')),
                ('is_active', models.BooleanField(default=True, help_text='Of deze tag beschikbaar is voor gebruik', verbose_name='actief')),
            ],
            options={
                'verbose_name': 'project tag',
                'verbose_name_plural': 'project tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unieke identificatie voor dit object', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Datum en tijd wanneer dit object aangemaakt is', verbose_name='aangemaakt op')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Datum en tijd wanneer dit object voor het laatst bijgewerkt is', verbose_name='bijgewerkt op')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicatie of dit object zacht verwijderd is', verbose_name='verwijderd')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Datum en tijd wanneer dit object zacht verwijderd is', null=True, verbose_name='verwijderd op')),
                ('version', models.PositiveIntegerField(default=1, help_text='Versienummer voor optimistic locking', verbose_name='versie')),
                ('project_number', models.CharField(editable=False, help_text='Uniek projectnummer gegenereerd door het systeem', max_length=50, unique=True, verbose_name='projectnummer')),
                ('name', models.CharField(help_text='Naam van het project', max_length=200, verbose_name='projectnaam')),
                ('description', models.TextField(blank=True, help_text='Gedetailleerde beschrijving van het project', verbose_name='beschrijving')),
                ('status', models.CharField(choices=[('draft', 'Concept'), ('planning', 'In planning'), ('active', 'Actief'), ('on_hold', 'Gepauzeerd'), ('completed', 'Voltooid'), ('cancelled', 'Geannuleerd'), ('archived', 'Gearchiveerd')], default='draft', help_text='Huidige status van het project', max_length=20, verbose_name='status')),
                ('priority', models.CharField(choices=[('low', 'Laag'), ('medium', 'Medium'), ('high', 'Hoog'), ('urgent', 'Urgent')], default='medium', help_text='Prioriteit van het project', max_length=20, verbose_name='prioriteit')),
                ('start_date', models.DateField(blank=True, help_text='Geplande startdatum van het project', null=True, verbose_name='startdatum')),
                ('end_date', models.DateField(blank=True, help_text='Geplande einddatum van het project', null=True, verbose_name='einddatum')),
                ('actual_start_date', models.DateField(blank=True, help_text='Werkelijke startdatum van het project', null=True, verbose_name='werkelijke startdatum')),
                ('actual_end_date', models.DateField(blank=True, help_text='Werkelijke einddatum van het project', null=True, verbose_name='werkelijke einddatum')),
                ('budget', models.DecimalField(decimal_places=2, default=0, help_text='Totaal budget voor het project', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='budget')),
                ('currency', models.CharField(default='EUR', help_text='Valuta voor budget en kosten', max_length=3, verbose_name='valuta')),
                ('internal_notes', models.TextField(blank=True, help_text='Interne notities over het project', verbose_name='interne notities')),
                ('client_notes', models.TextField(blank=True, help_text='Notities voor de klant', verbose_name='klantnotities')),
                ('requirements', models.TextField(blank=True, help_text='Projectvereisten en specificaties', verbose_name='vereisten')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Datum/tijd wanneer het project is voltooid', null=True, verbose_name='voltooid op')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Datum/tijd wanneer het project is geannuleerd', null=True, verbose_name='geannuleerd op')),
                ('client', models.ForeignKey(help_text='Klant voor wie het project wordt uitgevoerd', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='clients.client', verbose_name='klant')),
                ('contact_person', models.ForeignKey(blank=True, help_text='Contactpersoon bij de klant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='clients.clientcontact', verbose_name='contactpersoon')),
                ('created_by', models.ForeignKey(blank=True, help_text='Gebruiker die dit object aangemaakt heeft', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='aangemaakt door')),
                ('project_manager', models.ForeignKey(blank=True, help_text='Projectmanager verantwoordelijk voor dit project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='projectmanager')),
                ('team_members', models.ManyToManyField(blank=True, help_text='Teamleden die aan dit project werken', related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='teamleden')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Gebruiker die dit object voor het laatst bijgewerkt heeft', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='bijgewerkt door')),
                ('category', models.ForeignKey(blank=True, help_text='Categorie van het project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectcategory', verbose_name='categorie')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags voor categorisatie', related_name='projects', to='projects.projecttag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projecten',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project_number'], name='projects_pr_project_338cf3_idx'), models.Index(fields=['status', 'priority'], name='projects_pr_status_d9e5a3_idx'), models.Index(fields=['client', 'status'], name='projects_pr_client__60b095_idx'), models.Index(fields=['project_manager', 'status'], name='projects_pr_project_980913_idx'), models.Index(fields=['start_date', 'end_date'], name='projects_pr_start_d_dfae95_idx')],
            },
        ),
    ]
