# Generated by Django 5.2.9 on 2025-12-10 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='naam')),
                ('status', models.CharField(choices=[('pending', 'In afwachting'), ('in_progress', 'Bezig'), ('completed', 'Voltooid')], default='pending', max_length=20, verbose_name='status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='vervaldatum')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='project')),
            ],
        ),
    ]
