# Generated by Django 5.2.9 on 2025-12-04 19:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='categorie naam')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='beschrijving')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_categories/', verbose_name='categorie afbeelding')),
                ('is_active', models.BooleanField(default=True, verbose_name='actief')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='weergave volgorde')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='meta titel')),
                ('meta_description', models.TextField(blank=True, verbose_name='meta beschrijving')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='meta keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'product categorie',
                'verbose_name_plural': 'product categorieën',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='product titel')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('short_description', models.TextField(max_length=500, verbose_name='korte beschrijving')),
                ('full_description', models.TextField(verbose_name='volledige beschrijving')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prijs')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='originele prijs')),
                ('is_on_sale', models.BooleanField(default=False, verbose_name='in de aanbieding')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='aanbiedingsprijs')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SKU')),
                ('stock_quantity', models.PositiveIntegerField(default=1, verbose_name='voorraad hoeveelheid')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name='lage voorraad drempel')),
                ('condition', models.CharField(choices=[('new', 'Nieuw'), ('like_new', 'Zo goed als nieuw'), ('good', 'Goed'), ('fair', 'Redelijk'), ('refurbished', 'Gerenoveerd')], default='good', max_length=20, verbose_name='conditie')),
                ('status', models.CharField(choices=[('available', 'Beschikbaar'), ('sold', 'Verkocht'), ('reserved', 'Gereserveerd'), ('pending', 'In afwachting')], default='available', max_length=20, verbose_name='status')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='merk')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='model')),
                ('dimensions', models.CharField(blank=True, help_text='Bijv: 120x80x60 cm', max_length=100, verbose_name='afmetingen')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='In kilogram', max_digits=8, null=True, verbose_name='gewicht')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='materiaal')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='kleur')),
                ('is_featured', models.BooleanField(default=False, verbose_name='uitgelicht')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='bestseller')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='aantal bekeken')),
                ('requires_assembly', models.BooleanField(default=False, verbose_name='montage nodig')),
                ('assembly_service_available', models.BooleanField(default=True, verbose_name='montageservice beschikbaar')),
                ('delivery_available', models.BooleanField(default=True, verbose_name='bezorging beschikbaar')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='meta titel')),
                ('meta_description', models.TextField(blank=True, verbose_name='meta beschrijving')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='meta keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='gepubliceerd op')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='products', to='products.productcategory', verbose_name='categorieën')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'producten',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='kenmerk naam')),
                ('value', models.CharField(max_length=200, verbose_name='waarde')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class, bijv.: fas fa-check', max_length=50, verbose_name='icoon')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='weergave volgorde')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product')),
            ],
            options={
                'verbose_name': 'product kenmerk',
                'verbose_name_plural': 'product kenmerken',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d/', verbose_name='afbeelding')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='alternatieve tekst')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='bijschrift')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='weergave volgorde')),
                ('is_primary', models.BooleanField(default=False, verbose_name='hoofdafbeelding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'product afbeelding',
                'verbose_name_plural': 'product afbeeldingen',
                'ordering': ['display_order', '-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], verbose_name='beoordeling')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='titel')),
                ('comment', models.TextField(verbose_name='opmerking')),
                ('reviewer_name', models.CharField(blank=True, max_length=100, verbose_name='naam beoordelaar')),
                ('reviewer_email', models.EmailField(blank=True, max_length=254, verbose_name='email beoordelaar')),
                ('is_approved', models.BooleanField(default=False, verbose_name='goedgekeurd')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='geverifieerde aankoop')),
                ('helpful_yes', models.PositiveIntegerField(default=0, verbose_name='handig - ja')),
                ('helpful_no', models.PositiveIntegerField(default=0, verbose_name='handig - nee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'product beoordeling',
                'verbose_name_plural': 'product beoordelingen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'product weergave',
                'verbose_name_plural': 'product weergaven',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_pr_status_041708_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'user')},
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['product', 'created_at'], name='products_pr_product_e6f684_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['created_at'], name='products_pr_created_b3bafb_idx'),
        ),
    ]
