from django.db.models.signals import post_save, pre_save, post_delete
from django.dispatch import receiver
from django.utils import timezone
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.conf import settings
from .models import Order, OrderItem, Payment, OrderHistory


@receiver(pre_save, sender=Order)
def track_order_changes(sender, instance, **kwargs):
    """
    Track wijzigingen aan orders voor audit trail.
    
    TECHNISCHE CONCEPTEN:
    - Field change detection
    - Status transition tracking
    - Audit logging preparation
    """
    if instance.pk:
        try:
            old_instance = Order.objects.get(pk=instance.pk)
            changed_fields = []
            
            # Vergelijk velden
            for field in Order._meta.fields:
                field_name = field.name
                if field_name not in ['updated_at', 'version', 'last_login']:
                    old_value = getattr(old_instance, field_name)
                    new_value = getattr(instance, field_name)
                    
                    if old_value != new_value:
                        changed_fields.append(field_name)
            
            # Bewaar voor post_save
            instance._changed_fields = changed_fields
            instance._old_status = old_instance.status
            instance._old_payment_status = old_instance.payment_status
            
        except Order.DoesNotExist:
            instance._changed_fields = []
            instance._old_status = None
            instance._old_payment_status = None


@receiver(post_save, sender=Order)
def log_order_history(sender, instance, created, **kwargs):
    """
    Log order wijzigingen in geschiedenis.
    
    TECHNISCHE CONCEPTEN:
    - Audit trail creation
    - User action logging
    - Email notifications
    """
    request = getattr(instance, '_request', None)
    
    # Bepaal actie
    if created:
        action = 'created'
        old_value = None
        new_value = None
    else:
        action = 'updated'
        
        # Speciale acties voor status wijzigingen
        if hasattr(instance, '_old_status') and instance._old_status != instance.status:
            action = 'status_changed'
            old_value = instance._old_status
            new_value = instance.status
        
        if (hasattr(instance, '_old_payment_status') and 
            instance._old_payment_status != instance.payment_status):
            action = 'payment_status_changed'
            old_value = instance._old_payment_status
            new_value = instance.payment_status
    
    # Maak geschiedenis entry
    OrderHistory.objects.create(
        order=instance,
        action=action,
        old_value=old_value,
        new_value=new_value,
        changed_fields=getattr(instance, '_changed_fields', []),
        changed_by=request.user if request and request.user.is_authenticated else None,
        ip_address=request.META.get('REMOTE_ADDR') if request else None,
        user_agent=request.META.get('HTTP_USER_AGENT') if request else None,
        notes=f"Auto-generated by system at {timezone.now()}"
    )
    
    # Stuur notificaties
    if action == 'status_changed' and instance._old_status != instance.status:
        send_order_status_notification(instance, instance._old_status, instance.status)
    
    if action == 'payment_status_changed' and instance._old_payment_status != instance.payment_status:
        send_payment_status_notification(instance, instance._old_payment_status, instance.payment_status)
    
    # Stuur herinnering bij achterstallige betaling
    if instance.payment_status == 'overdue' and instance.payment_due_date:
        send_overdue_payment_reminder(instance)


@receiver(post_save, sender=Order)
def update_stock_on_status_change(sender, instance, **kwargs):
    """
    Update voorraad bij order status wijzigingen.
    
    TECHNISCHE CONCEPTEN:
    - Inventory management integration
    - Stock level tracking
    - Business workflow automation
    """
    if hasattr(instance, '_old_status') and instance._old_status != instance.status:
        if instance.status == 'processing':
            # Reserveer voorraad
            reserve_stock_for_order(instance)
        elif instance.status == 'cancelled' and instance._old_status == 'processing':
            # Herstel voorraad
            restore_stock_for_order(instance)
        elif instance.status == 'shipped':
            # Verminder voorraad
            reduce_stock_for_order(instance)


@receiver(post_save, sender=OrderItem)
def update_order_totals(sender, instance, **kwargs):
    """
    Update order totalen bij wijziging van items.
    """
    # Forceer update van order om totalen te herberekenen
    instance.order.save(update_fields=['updated_at'])


@receiver(post_save, sender=Payment)
def update_order_payment_status(sender, instance, **kwargs):
    """
    Update order betaalstatus bij nieuwe betaling.
    """
    order = instance.order
    
    # Herbereken totaal betaald
    total_paid = order.payments.filter(status='completed').aggregate(
        total=Sum('amount')
    )['total'] or 0
    
    if total_paid >= order.total_incl_tax:
        order.payment_status = 'paid'
    elif total_paid > 0:
        order.payment_status = 'partially_paid'
    elif order.payment_due_date and timezone.now().date() > order.payment_due_date:
        order.payment_status = 'overdue'
    
    order.save(update_fields=['payment_status', 'updated_at'])


def send_order_status_notification(order, old_status, new_status):
    """
    Stuur notificatie bij status wijziging.
    """
    try:
        subject = f"Order {order.order_number} status gewijzigd naar {new_status}"
        
        context = {
            'order': order,
            'old_status': old_status,
            'new_status': new_status,
            'site_name': getattr(settings, 'SITE_NAME', 'Company Services'),
        }
        
        text_message = render_to_string('emails/order_status_change.txt', context)
        html_message = render_to_string('emails/order_status_change.html', context)
        
        # Stuur naar interne team
        send_mail(
            subject=subject,
            message=text_message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[settings.ADMIN_EMAIL],
            html_message=html_message,
            fail_silently=True
        )
        
        # Stuur naar klant bij bepaalde status wijzigingen
        if new_status in ['confirmed', 'processing', 'shipped', 'delivered']:
            send_mail(
                subject=f"Update over je order {order.order_number}",
                message=text_message,
                from_email=settings.DEFAULT_FROM_EMAIL,
                recipient_list=[order.client.email],
                html_message=html_message,
                fail_silently=True
            )
    
    except Exception as e:
        import logging
        logger = logging.getLogger(__name__)
        logger.error(f"Failed to send order status notification: {e}")


def send_payment_status_notification(order, old_status, new_status):
    """
    Stuur notificatie bij betaalstatus wijziging.
    """
    try:
        subject = f"Betaling status order {order.order_number} gewijzigd naar {new_status}"
        
        context = {
            'order': order,
            'old_status': old_status,
            'new_status': new_status,
            'site_name': getattr(settings, 'SITE_NAME', 'Company Services'),
        }
        
        text_message = render_to_string('emails/payment_status_change.txt', context)
        html_message = render_to_string('emails/payment_status_change.html', context)
        
        # Stuur naar financiële afdeling
        send_mail(
            subject=subject,
            message=text_message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[settings.FINANCE_EMAIL],
            html_message=html_message,
            fail_silently=True
        )
    
    except Exception as e:
        import logging
        logger = logging.getLogger(__name__)
        logger.error(f"Failed to send payment status notification: {e}")


def send_overdue_payment_reminder(order):
    """
    Stuur herinnering voor achterstallige betaling.
    """
    try:
        subject = f"Herinnering: Betaling order {order.order_number} is achterstallig"
        
        context = {
            'order': order,
            'days_overdue': order.days_overdue,
            'site_name': getattr(settings, 'SITE_NAME', 'Company Services'),
        }
        
        text_message = render_to_string('emails/overdue_payment_reminder.txt', context)
        html_message = render_to_string('emails/overdue_payment_reminder.html', context)
        
        # Stuur naar klant
        send_mail(
            subject=subject,
            message=text_message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[order.client.email],
            html_message=html_message,
            fail_silently=True
        )
        
        # Stuur naar financiële afdeling
        send_mail(
            subject=f"[Intern] Achterstallige betaling: {order.order_number}",
            message=text_message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[settings.FINANCE_EMAIL],
            html_message=html_message,
            fail_silently=True
        )
    
    except Exception as e:
        import logging
        logger = logging.getLogger(__name__)
        logger.error(f"Failed to send overdue payment reminder: {e}")


def reserve_stock_for_order(order):
    """
    Reserveer voorraad voor order.
    """
    try:
        for item in order.items.filter(item_type='product', product__isnull=False):
            product = item.product
            
            # Update gereserveerde voorraad
            if product.stock_tracking:
                # TODO: Implement stock reservation logic
                # product.reserved_stock += item.quantity
                # product.save(update_fields=['reserved_stock'])
                pass
    
    except Exception as e:
        import logging
        logger = logging.getLogger(__name__)
        logger.error(f"Failed to reserve stock for order {order.order_number}: {e}")


def restore_stock_for_order(order):
    """
    Herstel voorraad na order annulering.
    """
    try:
        for item in order.items.filter(item_type='product', product__isnull=False):
            product = item.product
            
            # Update gereserveerde voorraad
            if product.stock_tracking:
                # TODO: Implement stock restoration logic
                # product.reserved_stock -= item.quantity
                # product.save(update_fields=['reserved_stock'])
                pass
    
    except Exception as e:
        import logging
        logger = logging.getLogger(__name__)
        logger.error(f"Failed to restore stock for order {order.order_number}: {e}")


def reduce_stock_for_order(order):
    """
    Verminder voorraad na verzending.
    """
    try:
        for item in order.items.filter(item_type='product', product__isnull=False):
            product = item.product
            
            # Update actuele voorraad
            if product.stock_tracking:
                # TODO: Implement stock reduction logic
                # product.current_stock -= item.quantity
                # product.reserved_stock -= item.quantity
                # product.save(update_fields=['current_stock', 'reserved_stock'])
                pass
    
    except Exception as e:
        import logging
        logger = logging.getLogger(__name__)
        logger.error(f"Failed to reduce stock for order {order.order_number}: {e}")