# Generated by Django 5.2.9 on 2025-12-07 18:42

import django.core.validators
import django.db.models.deletion
import quotes.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Naam van de tag', max_length=50, unique=True, verbose_name='naam')),
                ('slug', models.SlugField(help_text='URL-vriendelijke naam', max_length=60, unique=True, verbose_name='slug')),
                ('color', models.CharField(default='#3498db', help_text='Hex kleurcode voor visualisatie', max_length=7, verbose_name='kleur')),
                ('description', models.TextField(blank=True, help_text='Beschrijving van wanneer deze tag gebruikt wordt', verbose_name='beschrijving')),
                ('is_active', models.BooleanField(default=True, help_text='Of deze tag beschikbaar is voor gebruik', verbose_name='actief')),
            ],
            options={
                'verbose_name': 'offerte tag',
                'verbose_name_plural': 'offerte tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Naam van het template', max_length=200, unique=True, verbose_name='naam')),
                ('description', models.TextField(blank=True, help_text='Beschrijving van wanneer dit template gebruikt wordt', verbose_name='beschrijving')),
                ('content', models.TextField(help_text='HTML/content template met placeholders', verbose_name='inhoud')),
                ('header', models.TextField(blank=True, help_text='Template voor koptekst', verbose_name='koptekst')),
                ('footer', models.TextField(blank=True, help_text='Template voor voettekst', verbose_name='voettekst')),
                ('css_styles', models.TextField(blank=True, help_text='Custom CSS voor opmaak', verbose_name='CSS stijlen')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=21.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='standaard btw percentage')),
                ('default_payment_terms', models.TextField(blank=True, verbose_name='standaard betalingsvoorwaarden')),
                ('default_validity_days', models.PositiveIntegerField(default=30, help_text='Standaard aantal dagen dat offerte geldig is', verbose_name='standaard geldigheidsduur (dagen)')),
                ('is_active', models.BooleanField(default=True, help_text='Of dit template beschikbaar is voor gebruik', verbose_name='actief')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='aangemaakt op')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='bijgewerkt op')),
            ],
            options={
                'verbose_name': 'offerte template',
                'verbose_name_plural': 'offerte templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Beschrijvende naam van de bijlage', max_length=200, verbose_name='naam')),
                ('file', models.FileField(help_text='Het geüploade bestand', upload_to='quote_attachments/%Y/%m/%d/', verbose_name='bestand')),
                ('file_type', models.CharField(blank=True, help_text='MIME type van het bestand', max_length=100, verbose_name='bestandstype')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Grootte in bytes', null=True, verbose_name='bestandsgrootte')),
                ('version', models.PositiveIntegerField(default=1, help_text='Versienummer van het document', verbose_name='versie')),
                ('is_primary', models.BooleanField(default=False, help_text='Is dit het hoofdofferte document?', verbose_name='hoofddocument')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='geüpload op')),
                ('description', models.TextField(blank=True, help_text='Extra beschrijving van de bijlage', verbose_name='beschrijving')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_attachments', to=settings.AUTH_USER_MODEL, verbose_name='geüpload door')),
            ],
            options={
                'verbose_name': 'offerte bijlage',
                'verbose_name_plural': 'offerte bijlagen',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unieke identificatie voor dit object', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Datum en tijd wanneer dit object aangemaakt is', verbose_name='aangemaakt op')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Datum en tijd wanneer dit object voor het laatst bijgewerkt is', verbose_name='bijgewerkt op')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicatie of dit object zacht verwijderd is', verbose_name='verwijderd')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Datum en tijd wanneer dit object zacht verwijderd is', null=True, verbose_name='verwijderd op')),
                ('version', models.PositiveIntegerField(default=1, help_text='Versienummer voor optimistic locking', verbose_name='versie')),
                ('quote_number', models.CharField(editable=False, help_text='Uniek offertenummer gegenereerd door het systeem', max_length=50, unique=True, verbose_name='offerte nummer')),
                ('reference', models.CharField(blank=True, help_text='Interne referentie of klantreferentie', max_length=100, null=True, verbose_name='referentie')),
                ('revision', models.PositiveIntegerField(default=1, help_text='Revisienummer van deze offerte', verbose_name='revisie')),
                ('status', models.CharField(choices=[('draft', 'Concept'), ('pending', 'In afwachting'), ('sent', 'Verzonden'), ('viewed', 'Bekeken'), ('negotiation', 'In onderhandeling'), ('accepted', 'Geaccepteerd'), ('rejected', 'Geweigerd'), ('expired', 'Verlopen'), ('cancelled', 'Geannuleerd'), ('converted', 'Omgezet naar order')], default='draft', help_text='Huidige status van de offerte', max_length=20, verbose_name='status')),
                ('priority', models.CharField(choices=[('low', 'Laag'), ('medium', 'Medium'), ('high', 'Hoog'), ('urgent', 'Urgent')], default='medium', help_text='Prioriteit voor behandeling', max_length=20, verbose_name='prioriteit')),
                ('currency', models.CharField(default='EUR', help_text='Valuta waarin de offerte is opgesteld (ISO 4217 code)', max_length=3, verbose_name='valuta')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, help_text='Wisselkoers t.o.v. basisvaluta', max_digits=10, verbose_name='wisselkoers')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=21.0, help_text='BTW percentage dat wordt toegepast', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='btw percentage')),
                ('tax_inclusive', models.BooleanField(default=True, help_text='Zijn de prijzen inclusief BTW?', verbose_name='btw inclusief')),
                ('valid_from', models.DateTimeField(auto_now_add=True, help_text='Datum/tijd vanaf wanneer de offerte geldig is', verbose_name='geldig vanaf')),
                ('valid_until', models.DateTimeField(help_text='Datum/tijd tot wanneer de offerte geldig is', verbose_name='geldig tot')),
                ('delivery_date', models.DateTimeField(blank=True, help_text='Gewenste leverdatum', null=True, verbose_name='leverdatum')),
                ('payment_terms', models.TextField(blank=True, help_text='Specifieke betalingsvoorwaarden voor deze offerte', verbose_name='betalingsvoorwaarden')),
                ('delivery_terms', models.TextField(blank=True, help_text='Specifieke leveringsvoorwaarden voor deze offerte', verbose_name='leveringsvoorwaarden')),
                ('internal_notes', models.TextField(blank=True, help_text='Interne notities voor het team', verbose_name='interne notities')),
                ('client_notes', models.TextField(blank=True, help_text='Notities die op de offerte voor de klant verschijnen', verbose_name='klantnotities')),
                ('terms_conditions', models.TextField(blank=True, help_text='Algemene voorwaarden van toepassing', verbose_name='algemene voorwaarden')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Datum/tijd wanneer de offerte naar de klant is verzonden', null=True, verbose_name='verzonden op')),
                ('viewed_at', models.DateTimeField(blank=True, help_text='Datum/tijd wanneer de klant de offerte heeft bekeken', null=True, verbose_name='bekeken op')),
                ('responded_at', models.DateTimeField(blank=True, help_text='Datum/tijd van klantreactie', null=True, verbose_name='beantwoord op')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='Datum/tijd wanneer de offerte is geaccepteerd', null=True, verbose_name='geaccepteerd op')),
                ('expired_at', models.DateTimeField(blank=True, help_text='Datum/tijd wanneer de offerte automatisch is verlopen', null=True, verbose_name='verlopen op')),
                ('conversion_rate', models.FloatField(blank=True, help_text='Percentage van de totale waarde dat is geconverteerd', null=True, verbose_name='conversie percentage')),
                ('billing_address', models.ForeignKey(blank=True, help_text='Factuuradres voor deze offerte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_quotes', to='clients.address', verbose_name='factuuradres')),
                ('client', models.ForeignKey(help_text='Klant waarvoor de offerte is opgesteld', on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='clients.client', verbose_name='klant')),
                ('contact_person', models.ForeignKey(blank=True, help_text='Specifieke contactpersoon bij de klant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='clients.clientcontact', verbose_name='contactpersoon')),
                ('converted_to_order', models.ForeignKey(blank=True, help_text='Order waar deze offerte naar is omgezet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quote', to='orders.order', verbose_name='omgezet naar order')),
                ('created_by', models.ForeignKey(blank=True, help_text='Gebruiker die dit object aangemaakt heeft', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='aangemaakt door')),
                ('delivery_address', models.ForeignKey(blank=True, help_text='Afleveradres voor deze offerte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_quotes', to='clients.address', verbose_name='afleveradres')),
                ('parent_quote', models.ForeignKey(blank=True, help_text='Originele offerte waarvan dit een revisie is', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='quotes.quote', verbose_name='originele offerte')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Gebruiker die dit object voor het laatst bijgewerkt heeft', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='bijgewerkt door')),
                ('attachments', models.ManyToManyField(blank=True, help_text='Documenten en bijlagen bij de offerte', related_name='quotes', to='quotes.quoteattachment', verbose_name='bijlagen')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags voor categorisatie en filtering', related_name='quotes', to='quotes.quotetag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'offerte',
                'verbose_name_plural': 'offertes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('quote', 'Quote'), ('contract', 'Contract'), ('attachment', 'Attachment'), ('other', 'Other')], default='attachment', max_length=20)),
                ('file', models.FileField(max_length=255, upload_to=quotes.models.quote_document_upload_path)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='quotes.quote')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quote Document',
                'verbose_name_plural': 'Quote Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Aangemaakt'), ('updated', 'Bijgewerkt'), ('status_changed', 'Status gewijzigd'), ('sent', 'Verzonden'), ('viewed', 'Bekeken'), ('accepted', 'Geaccepteerd'), ('rejected', 'Geweigerd'), ('converted', 'Omgezet'), ('revision', 'Revisie aangemaakt')], max_length=50, verbose_name='actie')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='oude waarde')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='nieuwe waarde')),
                ('changed_fields', models.JSONField(default=list, help_text='Lijst van gewijzigde veldnamen', verbose_name='gewijzigde velden')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='gewijzigd op')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP adres')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='user agent')),
                ('notes', models.TextField(blank=True, help_text='Extra informatie over de wijziging', verbose_name='notities')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_changes', to=settings.AUTH_USER_MODEL, verbose_name='gewijzigd door')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='quotes.quote', verbose_name='offerte')),
            ],
            options={
                'verbose_name': 'offerte geschiedenis',
                'verbose_name_plural': 'offerte geschiedenis',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(default=1, help_text='Volgnummer in de offerte', verbose_name='regelnummer')),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('service', 'Dienst'), ('material', 'Materiaal'), ('labor', 'Arbeid'), ('other', 'Overig')], default='product', help_text='Type van dit item', max_length=20, verbose_name='type item')),
                ('description', models.TextField(help_text='Gedetailleerde omschrijving van het item', verbose_name='omschrijving')),
                ('specification', models.TextField(blank=True, help_text='Technische specificaties of aanvullende informatie', verbose_name='specificatie')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, help_text='Aantal eenheden', max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='aantal')),
                ('unit', models.CharField(default='stuk', help_text='Eenheid (stuk, uur, meter, etc.)', max_length=20, verbose_name='eenheid')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Prijs per eenheid exclusief BTW', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='eenheidsprijs')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Kostprijs per eenheid (voor winstberekening)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='kostprijs')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Korting percentage op dit item', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='kortingspercentage')),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Specifiek BTW percentage voor dit item (laat leeg voor offerte default)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='btw percentage')),
                ('delivery_week', models.PositiveIntegerField(blank=True, help_text='Geplande leverweek (optioneel)', null=True, verbose_name='leverweek')),
                ('notes', models.TextField(blank=True, help_text='Interne notities over dit item', verbose_name='notities')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='products.product', verbose_name='product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote', verbose_name='offerte')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='services.service', verbose_name='dienst')),
            ],
            options={
                'verbose_name': 'offerte item',
                'verbose_name_plural': 'offerte items',
                'ordering': ['line_number'],
                'unique_together': {('quote', 'line_number')},
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['quote_number'], name='quotes_quot_quote_n_6770d1_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status', 'valid_until'], name='quotes_quot_status_3ae330_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['client', 'created_at'], name='quotes_quot_client__1b5e56_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status', 'priority'], name='quotes_quot_status_9fd1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['valid_until'], name='quotes_quot_valid_u_e269ff_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['sent_at'], name='quotes_quot_sent_at_2f5062_idx'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__gt', models.F('valid_from'))), name='valid_until_after_valid_from'),
        ),
    ]
