# Generated by Django 5.2.9 on 2025-12-07 18:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='dienst naam')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('short_description', models.TextField(max_length=500, verbose_name='korte beschrijving')),
                ('full_description', models.TextField(verbose_name='volledige beschrijving')),
                ('benefits', models.TextField(blank=True, help_text='Lijst van voordelen (gebruik bullets)', verbose_name='voordelen')),
                ('process', models.TextField(blank=True, help_text='Beschrijving van de werkwijze', verbose_name='werkwijze')),
                ('has_fixed_price', models.BooleanField(default=False, verbose_name='vaste prijs')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vaste prijs')),
                ('price_description', models.CharField(blank=True, help_text='Bijv: "Vanaf €50" of "Op aanvraag"', max_length=200, verbose_name='prijs beschrijving')),
                ('estimated_time', models.CharField(blank=True, help_text='Bijv: "2-4 uur" of "1 dag"', max_length=100, verbose_name='geschatte tijd')),
                ('is_popular', models.BooleanField(default=False, verbose_name='populaire dienst')),
                ('is_featured', models.BooleanField(default=False, verbose_name='uitgelicht')),
                ('is_active', models.BooleanField(default=True, verbose_name='actief')),
                ('requirements', models.TextField(blank=True, help_text='Wat heeft de klant nodig?', verbose_name='vereisten')),
                ('requires_quote', models.BooleanField(default=True, verbose_name='offerte nodig')),
                ('can_book_online', models.BooleanField(default=False, verbose_name='online boekbaar')),
                ('has_emergency_service', models.BooleanField(default=False, verbose_name='spoedservice')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='meta titel')),
                ('meta_description', models.TextField(blank=True, verbose_name='meta beschrijving')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='meta keywords')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='aantal bekeken')),
                ('quote_requests_count', models.PositiveIntegerField(default=0, verbose_name='aantal offerte aanvragen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='gepubliceerd op')),
            ],
            options={
                'verbose_name': 'dienst',
                'verbose_name_plural': 'diensten',
                'ordering': ['category__display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='categorie naam')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('category_type', models.CharField(choices=[('demontage_montage', 'Demontage & Montage'), ('mobel_verkauf', 'Möbel- & Elektroverkauf'), ('auto_ankauf', 'Auto-Ankauf & -Verkauf'), ('autowerkstatt', 'Autowerkstatt & Karosserie'), ('renovierung', 'Renovierung & Wiederaufbau'), ('entsorgung', 'Entsorgung'), ('transport', 'Transport & Verpackung'), ('import_export', 'Import & Export')], max_length=50, unique=True, verbose_name='categorie type')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class, bijv.: fas fa-tools', max_length=50, verbose_name='icoon')),
                ('description', models.TextField(verbose_name='beschrijving')),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_categories/', verbose_name='categorie afbeelding')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='weergave volgorde')),
                ('is_active', models.BooleanField(default=True, verbose_name='actief')),
                ('show_on_homepage', models.BooleanField(default=False, verbose_name='toon op homepage')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='meta titel')),
                ('meta_description', models.TextField(blank=True, verbose_name='meta beschrijving')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='meta keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'dienst categorie',
                'verbose_name_plural': 'dienst categorieën',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='vraag')),
                ('answer', models.TextField(verbose_name='antwoord')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='weergave volgorde')),
                ('is_active', models.BooleanField(default=True, verbose_name='actief')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.service')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='categorie'),
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='titel')),
                ('description', models.TextField(blank=True, verbose_name='beschrijving')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, verbose_name='icoon')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='weergave volgorde')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service')),
            ],
            options={
                'verbose_name': 'dienst kenmerk',
                'verbose_name_plural': 'dienst kenmerken',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/%Y/%m/%d/', verbose_name='afbeelding')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='bijschrift')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='alternatieve tekst')),
                ('is_before_image', models.BooleanField(default=False, verbose_name='voor afbeelding')),
                ('is_after_image', models.BooleanField(default=False, verbose_name='na afbeelding')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='weergave volgorde')),
                ('is_primary', models.BooleanField(default=False, verbose_name='hoofdafbeelding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service')),
            ],
            options={
                'verbose_name': 'dienst afbeelding',
                'verbose_name_plural': 'dienst afbeeldingen',
                'ordering': ['display_order', '-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='pakket naam')),
                ('description', models.TextField(verbose_name='beschrijving')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prijs')),
                ('duration', models.CharField(blank=True, help_text='Bijv: "3 uur" of "1 dag"', max_length=100, verbose_name='duur')),
                ('includes', models.TextField(blank=True, help_text='Wat is inbegrepen (lijst)', verbose_name='inclusief')),
                ('excludes', models.TextField(blank=True, help_text='Wat is niet inbegrepen (lijst)', verbose_name='exclusief')),
                ('is_popular', models.BooleanField(default=False, verbose_name='populair pakket')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='weergave volgorde')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='services.service')),
            ],
            options={
                'verbose_name': 'dienst pakket',
                'verbose_name_plural': 'dienst pakketten',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='services.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dienst weergave',
                'verbose_name_plural': 'dienst weergaven',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='klant naam')),
                ('client_location', models.CharField(blank=True, max_length=100, verbose_name='locatie klant')),
                ('client_company', models.CharField(blank=True, max_length=100, verbose_name='bedrijf klant')),
                ('content', models.TextField(verbose_name='beoordeling')),
                ('rating', models.PositiveIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], verbose_name='beoordeling')),
                ('is_approved', models.BooleanField(default=False, verbose_name='goedgekeurd')),
                ('is_featured', models.BooleanField(default=False, verbose_name='uitgelicht')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='weergave volgorde')),
                ('project_date', models.DateField(blank=True, null=True, verbose_name='project datum')),
                ('project_description', models.CharField(blank=True, max_length=200, verbose_name='project beschrijving')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='services.service', verbose_name='dienst')),
            ],
            options={
                'verbose_name': 'testimonial',
                'verbose_name_plural': 'testimonials',
                'ordering': ['-is_featured', 'display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='stad')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='postcode')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='regio')),
                ('is_active', models.BooleanField(default=True, verbose_name='actief')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='services.service')),
            ],
            options={
                'verbose_name': 'dienst gebied',
                'verbose_name_plural': 'dienst gebieden',
                'unique_together': {('service', 'city', 'postal_code')},
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['slug', 'is_active'], name='services_se_slug_f039d2_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_active'], name='services_se_categor_b50c86_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_popular', 'is_active'], name='services_se_is_popu_05a630_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceview',
            index=models.Index(fields=['service', 'created_at'], name='services_se_service_379532_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceview',
            index=models.Index(fields=['created_at'], name='services_se_created_8f39c0_idx'),
        ),
    ]
