from django.db.models.signals import post_save, pre_save, post_delete
from django.dispatch import receiver
from django.utils import timezone
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.conf import settings
from .models import Quote, QuoteHistory


@receiver(pre_save, sender=Quote)
def track_quote_changes(sender, instance, **kwargs):
    """
    Track wijzigingen aan offertes voor audit trail.
    
    TECHNISCHE CONCEPTEN:
    - Field change detection
    - JSON diff calculation
    - Audit logging
    """
    if instance.pk:
        try:
            old_instance = Quote.objects.get(pk=instance.pk)
            changed_fields = []
            
            # Vergelijk velden
            for field in Quote._meta.fields:
                field_name = field.name
                if field_name not in ['updated_at', 'version']:
                    old_value = getattr(old_instance, field_name)
                    new_value = getattr(instance, field_name)
                    
                    if old_value != new_value:
                        changed_fields.append(field_name)
            
            # Bewaar voor post_save
            instance._changed_fields = changed_fields
            instance._old_status = old_instance.status
            
        except Quote.DoesNotExist:
            instance._changed_fields = []
            instance._old_status = None


@receiver(post_save, sender=Quote)
def log_quote_history(sender, instance, created, **kwargs):
    """
    Log offerte wijzigingen in geschiedenis.
    
    TECHNISCHE CONCEPTEN:
    - Audit trail creation
    - User action logging
    - Email notifications
    """
    request = getattr(instance, '_request', None)
    
    # Bepaal actie
    if created:
        action = 'created'
        old_value = None
        new_value = None
    else:
        action = 'updated'
        old_value = instance._old_status if hasattr(instance, '_old_status') else None
        new_value = instance.status
        # Status change is special
        if old_value != new_value:
            action = 'status_changed'
    
    # Maak geschiedenis entry
    QuoteHistory.objects.create(
        quote=instance,
        action=action,
        old_value=old_value,
        new_value=new_value,
        changed_fields=getattr(instance, '_changed_fields', []),
        changed_by=request.user if request and request.user.is_authenticated else None,
        ip_address=request.META.get('REMOTE_ADDR') if request else None,
        user_agent=request.META.get('HTTP_USER_AGENT') if request else None,
        notes=f"Auto-generated by system at {timezone.now()}"
    )
    
    # Stuur notificaties bij status wijziging
    if action == 'status_changed' and old_value != new_value:
        send_quote_status_notification(instance, old_value, new_value)
    
    # Stuur herinnering bij bijna verlopen offerte
    if instance.days_until_expiry == 3:  # 3 dagen voor verlopen
        send_expiry_reminder(instance)


@receiver(post_save, sender=Quote)
def generate_pdf_on_save(sender, instance, created, **kwargs):
    """
    Genereer PDF wanneer offerte verzonden wordt.
    
    TECHNISCHE CONCEPTEN:
    - Async task triggering
    - PDF generation
    - File attachment
    """
    if instance.status == 'sent' and not instance.attachments.filter(is_primary=True).exists():
        # TODO: Trigger async PDF generation
        # generate_quote_pdf.delay(instance.id)
        pass


@receiver(post_save, sender=Quote)
def create_followup_task(sender, instance, **kwargs):
    """
    Maak follow-up taak voor offerte.
    
    TECHNISCHE CONCEPTEN:
    - Workflow automation
    - Task management integration
    """
    if instance.status == 'sent':
        # TODO: Create follow-up task in 7 days
        # create_followup_task.delay(instance.id, days=7)
        pass


def send_quote_status_notification(quote, old_status, new_status):
    """
    Stuur notificatie bij status wijziging.
    """
    try:
        subject = f"Offerte {quote.quote_number} status gewijzigd naar {new_status}"
        
        context = {
            'quote': quote,
            'old_status': old_status,
            'new_status': new_status,
            'site_name': getattr(settings, 'SITE_NAME', 'Onze Website'),
        }
        
        text_message = render_to_string('emails/quote_status_change.txt', context)
        html_message = render_to_string('emails/quote_status_change.html', context)
        
        # Stuur naar interne team
        send_mail(
            subject=subject,
            message=text_message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[settings.ADMIN_EMAIL],
            html_message=html_message,
            fail_silently=True
        )
        
        # Stuur naar klant bij bepaalde status wijzigingen
        if new_status in ['sent', 'accepted', 'rejected']:
            send_mail(
                subject=f"Update over je offerte {quote.quote_number}",
                message=text_message,
                from_email=settings.DEFAULT_FROM_EMAIL,
                recipient_list=[quote.client.email],
                html_message=html_message,
                fail_silently=True
            )
    
    except Exception as e:
        import logging
        logger = logging.getLogger(__name__)
        logger.error(f"Failed to send quote status notification: {e}")


def send_expiry_reminder(quote):
    """
    Stuur herinnering voor bijna verlopen offerte.
    """
    try:
        subject = f"Herinnering: Offerte {quote.quote_number} verloopt binnen {quote.days_until_expiry} dagen"
        
        context = {
            'quote': quote,
            'days_until_expiry': quote.days_until_expiry,
            'site_name': getattr(settings, 'SITE_NAME', 'Onze Website'),
        }
        
        text_message = render_to_string('emails/quote_expiry_reminder.txt', context)
        html_message = render_to_string('emails/quote_expiry_reminder.html', context)
        
        # Stuur naar sales team
        send_mail(
            subject=subject,
            message=text_message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[settings.SALES_EMAIL],
            html_message=html_message,
            fail_silently=True
        )
    
    except Exception as e:
        import logging
        logger = logging.getLogger(__name__)
        logger.error(f"Failed to send expiry reminder: {e}")