# Generated by Django 5.2.9 on 2025-12-07 18:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('quotes', '__first__'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Naam van de categorie', max_length=100, unique=True, verbose_name='naam')),
                ('slug', models.SlugField(help_text='URL-vriendelijke naam', max_length=120, unique=True, verbose_name='slug')),
                ('category_type', models.CharField(choices=[('general', 'Algemeen'), ('sales', 'Verkoop'), ('support', 'Ondersteuning'), ('technical', 'Technisch'), ('complaint', 'Klacht'), ('quote_request', 'Offerte aanvraag'), ('service_request', 'Dienst aanvraag'), ('feedback', 'Feedback'), ('other', 'Overig')], default='general', help_text='Type categorie voor interne routing', max_length=20, verbose_name='categorie type')),
                ('description', models.TextField(blank=True, help_text='Beschrijving van wanneer deze categorie gebruikt moet worden', verbose_name='beschrijving')),
                ('email_recipient', models.EmailField(blank=True, help_text='Specifieke e-mail voor deze categorie (laat leeg voor default)', max_length=254, null=True, verbose_name='e-mail ontvanger')),
                ('is_active', models.BooleanField(default=True, help_text='Of deze categorie beschikbaar is voor gebruik', verbose_name='actief')),
                ('priority', models.PositiveIntegerField(default=5, help_text='Prioriteit (1=hoogste, 10=laagste) voor response tijd', verbose_name='prioriteit')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='contact.contactcategory', verbose_name='hoofdcategorie')),
            ],
            options={
                'verbose_name': 'contactcategorie',
                'verbose_name_plural': 'contactcategorieën',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unieke identificatie voor dit object', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Datum en tijd wanneer dit object aangemaakt is', verbose_name='aangemaakt op')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Datum en tijd wanneer dit object voor het laatst bijgewerkt is', verbose_name='bijgewerkt op')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicatie of dit object zacht verwijderd is', verbose_name='verwijderd')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Datum en tijd wanneer dit object zacht verwijderd is', null=True, verbose_name='verwijderd op')),
                ('version', models.PositiveIntegerField(default=1, help_text='Versienummer voor optimistic locking', verbose_name='versie')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('reference_number', models.CharField(editable=False, help_text='Uniek referentienummer voor dit bericht', max_length=50, unique=True, verbose_name='referentie nummer')),
                ('full_name', models.CharField(help_text='Voor- en achternaam van de verzender', max_length=200, verbose_name='volledige naam')),
                ('email', models.EmailField(help_text='E-mailadres voor antwoord', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='e-mailadres')),
                ('phone_number', models.CharField(blank=True, help_text='Optioneel telefoonnummer', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Telefoonnummer moet in het formaat: '+31612345678'. Maximaal 15 cijfers.", regex='^\\+?1?\\d{9,15}$')], verbose_name='telefoonnummer')),
                ('company_name', models.CharField(blank=True, help_text='Optionele bedrijfsnaam', max_length=200, null=True, verbose_name='bedrijfsnaam')),
                ('subject', models.CharField(help_text='Onderwerp van het bericht', max_length=200, verbose_name='onderwerp')),
                ('message', models.TextField(help_text='Inhoud van het bericht', verbose_name='bericht')),
                ('status', models.CharField(choices=[('new', 'Nieuw'), ('read', 'Gelezen'), ('in_progress', 'In behandeling'), ('awaiting_reply', 'Wacht op antwoord'), ('resolved', 'Afgehandeld'), ('closed', 'Gesloten'), ('spam', 'Spam')], default='new', help_text='Huidige status van het bericht', max_length=20, verbose_name='status')),
                ('priority', models.PositiveIntegerField(default=5, help_text='Prioriteit van het bericht (1=hoogste, 10=laagste)', verbose_name='prioriteit')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP adres van de verzender', null=True, verbose_name='IP adres')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device informatie', null=True, verbose_name='user agent')),
                ('page_url', models.URLField(blank=True, help_text='URL waar het formulier is ingediend', max_length=500, null=True, verbose_name='pagina URL')),
                ('response_notes', models.TextField(blank=True, help_text='Interne notities over de afhandeling', null=True, verbose_name='antwoord notities')),
                ('responded_at', models.DateTimeField(blank=True, help_text='Datum/tijd van laatste antwoord', null=True, verbose_name='beantwoord op')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Medewerker die dit bericht behandelt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='toegewezen aan')),
                ('category', models.ForeignKey(help_text='Categorie van het bericht', on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='contact.contactcategory', verbose_name='categorie')),
                ('created_by', models.ForeignKey(blank=True, help_text='Gebruiker die dit object aangemaakt heeft', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='aangemaakt door')),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='products.product', verbose_name='gerelateerd product')),
                ('related_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='quotes.quote', verbose_name='gerelateerde offerte')),
                ('related_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='services.service', verbose_name='gerelateerde dienst')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Gebruiker die dit object voor het laatst bijgewerkt heeft', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='bijgewerkt door')),
            ],
            options={
                'verbose_name': 'contactbericht',
                'verbose_name_plural': 'contactberichten',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Bijlage bij het bericht', upload_to='contact_attachments/%Y/%m/%d/', verbose_name='bestand')),
                ('file_name', models.CharField(blank=True, help_text='Originele bestandsnaam', max_length=255, verbose_name='bestandsnaam')),
                ('file_type', models.CharField(blank=True, help_text='MIME type van het bestand', max_length=100, verbose_name='bestandstype')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Grootte in bytes', null=True, verbose_name='bestandsgrootte')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='geüpload op')),
                ('is_safe', models.BooleanField(default=True, help_text='Indicatie of het bestand veilig is gescand', verbose_name='veilig gescand')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contact.contactmessage', verbose_name='bericht')),
            ],
            options={
                'verbose_name': 'contactbijlage',
                'verbose_name_plural': 'contactbijlagen',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='E-mailadres voor nieuwsbrief', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='e-mailadres')),
                ('full_name', models.CharField(blank=True, help_text='Optionele volledige naam', max_length=200, null=True, verbose_name='volledige naam')),
                ('subscription_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='inschrijvingstoken')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Heeft de gebruiker de inschrijving bevestigd?', verbose_name='bevestigd')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='bevestigd op')),
                ('subscription_preferences', models.JSONField(default=dict, help_text='Voorkeuren voor type updates', verbose_name='inschrijvingsvoorkeuren')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP adres tijdens inschrijving', null=True, verbose_name='IP adres')),
                ('is_active', models.BooleanField(default=True, help_text='Is de inschrijving actief?', verbose_name='actief')),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uitschrijftoken')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='uitgeschreven op')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='aangemaakt op')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='bijgewerkt op')),
            ],
            options={
                'verbose_name': 'nieuwsbriefinschrijving',
                'verbose_name_plural': 'nieuwsbriefinschrijvingen',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'is_active'], name='contact_new_email_009dea_idx'), models.Index(fields=['is_confirmed', 'is_active'], name='contact_new_is_conf_4c5b4e_idx'), models.Index(fields=['created_at'], name='contact_new_created_368c3d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contactcategory',
            index=models.Index(fields=['slug', 'is_active'], name='contact_con_slug_5ae269_idx'),
        ),
        migrations.AddIndex(
            model_name='contactcategory',
            index=models.Index(fields=['category_type', 'is_active'], name='contact_con_categor_b01fc2_idx'),
        ),
        migrations.AddIndex(
            model_name='contactcategory',
            index=models.Index(fields=['priority'], name='contact_con_priorit_640272_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['uuid'], name='contact_con_uuid_8b67f1_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['reference_number'], name='contact_con_referen_b9d09a_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['status', 'created_at'], name='contact_con_status_402fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['email', 'created_at'], name='contact_con_email_02ea8f_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['category', 'status'], name='contact_con_categor_038da1_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['priority', 'created_at'], name='contact_con_priorit_d9c4dd_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['assigned_to', 'status'], name='contact_con_assigne_c37afd_idx'),
        ),
        migrations.AddIndex(
            model_name='contactattachment',
            index=models.Index(fields=['message', 'uploaded_at'], name='contact_con_message_ab49e4_idx'),
        ),
    ]
