# Generated by Django 5.2.9 on 2025-12-07 18:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Naam van de tag', max_length=50, unique=True, verbose_name='naam')),
                ('slug', models.SlugField(help_text='URL-vriendelijke naam', max_length=60, unique=True, verbose_name='slug')),
                ('color', models.CharField(default='#3498db', help_text='Hex kleurcode voor visualisatie', max_length=7, verbose_name='kleur')),
                ('description', models.TextField(blank=True, help_text='Beschrijving van wanneer deze tag gebruikt wordt', verbose_name='beschrijving')),
                ('is_active', models.BooleanField(default=True, help_text='Of deze tag beschikbaar is voor gebruik', verbose_name='actief')),
            ],
            options={
                'verbose_name': 'klant tag',
                'verbose_name_plural': 'klant tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unieke identificatie voor dit object', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Datum en tijd wanneer dit object aangemaakt is', verbose_name='aangemaakt op')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Datum en tijd wanneer dit object voor het laatst bijgewerkt is', verbose_name='bijgewerkt op')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicatie of dit object zacht verwijderd is', verbose_name='verwijderd')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Datum en tijd wanneer dit object zacht verwijderd is', null=True, verbose_name='verwijderd op')),
                ('version', models.PositiveIntegerField(default=1, help_text='Versienummer voor optimistic locking', verbose_name='versie')),
                ('client_number', models.CharField(editable=False, help_text='Uniek klantnummer gegenereerd door het systeem', max_length=50, unique=True, verbose_name='klantnummer')),
                ('company_name', models.CharField(blank=True, help_text='Officiële bedrijfsnaam (voor bedrijven)', max_length=200, verbose_name='bedrijfsnaam')),
                ('legal_name', models.CharField(blank=True, help_text='Juridische naam (kan afwijken van bedrijfsnaam)', max_length=200, verbose_name='juridische naam')),
                ('client_type', models.CharField(choices=[('individual', 'Particulier'), ('business', 'Bedrijf'), ('government', 'Overheid'), ('non_profit', 'Non-profit'), ('partner', 'Partner')], default='business', help_text='Type klant', max_length=20, verbose_name='klanttype')),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Actief'), ('inactive', 'Inactief'), ('suspended', 'Geschorst'), ('former', 'Voormalig')], default='prospect', help_text='Huidige status van de klant', max_length=20, verbose_name='status')),
                ('email', models.EmailField(help_text='Primair e-mailadres', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='e-mailadres')),
                ('phone', models.CharField(help_text='Primair telefoonnummer', max_length=17, validators=[django.core.validators.RegexValidator(message="Telefoonnummer moet in het formaat: '+31612345678'. Maximaal 15 cijfers.", regex='^\\+?1?\\d{9,15}$')], verbose_name='telefoonnummer')),
                ('website', models.URLField(blank=True, help_text='Website URL', null=True, validators=[django.core.validators.URLValidator()], verbose_name='website')),
                ('street', models.CharField(blank=True, help_text='Straatnaam en huisnummer', max_length=200, verbose_name='straat')),
                ('postal_code', models.CharField(blank=True, help_text='Postcode', max_length=10, verbose_name='postcode')),
                ('city', models.CharField(blank=True, help_text='Stad', max_length=100, verbose_name='stad')),
                ('country', models.CharField(default='Nederland', help_text='Land', max_length=100, verbose_name='land')),
                ('tax_number', models.CharField(blank=True, help_text='BTW-nummer', max_length=50, null=True, verbose_name='btw-nummer')),
                ('chamber_of_commerce', models.CharField(blank=True, help_text='Kamer van Koophandel nummer', max_length=50, null=True, verbose_name='kvk-nummer')),
                ('industry', models.CharField(blank=True, help_text='Industrie of branche', max_length=100, verbose_name='branche')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Maximaal kredietbedrag', max_digits=12, verbose_name='kredietlimiet')),
                ('payment_terms', models.CharField(default='30 dagen', help_text='Standaard betalingsvoorwaarden', max_length=50, verbose_name='betalingsvoorwaarden')),
                ('currency', models.CharField(default='EUR', help_text='Voorkeursvaluta', max_length=3, verbose_name='valuta')),
                ('source', models.CharField(blank=True, help_text='Hoe is de klant bij ons terechtgekomen?', max_length=100, verbose_name='bron')),
                ('internal_notes', models.TextField(blank=True, help_text='Interne notities over deze klant', verbose_name='interne notities')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Accountmanager of verkoper', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL, verbose_name='toegewezen aan')),
                ('created_by', models.ForeignKey(blank=True, help_text='Gebruiker die dit object aangemaakt heeft', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='aangemaakt door')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Gebruiker die dit object voor het laatst bijgewerkt heeft', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='bijgewerkt door')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags voor categorisatie', related_name='clients', to='clients.clienttag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'klant',
                'verbose_name_plural': 'klanten',
                'ordering': ['company_name', 'client_number'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Voornaam', max_length=100, verbose_name='voornaam')),
                ('last_name', models.CharField(help_text='Achternaam', max_length=100, verbose_name='achternaam')),
                ('email', models.EmailField(help_text='E-mailadres van de contactpersoon', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='e-mailadres')),
                ('phone', models.CharField(help_text='Telefoonnummer van de contactpersoon', max_length=17, validators=[django.core.validators.RegexValidator(message="Telefoonnummer moet in het formaat: '+31612345678'. Maximaal 15 cijfers.", regex='^\\+?1?\\d{9,15}$')], verbose_name='telefoonnummer')),
                ('mobile', models.CharField(blank=True, help_text='Mobiel telefoonnummer', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Telefoonnummer moet in het formaat: '+31612345678'. Maximaal 15 cijfers.", regex='^\\+?1?\\d{9,15}$')], verbose_name='mobiel nummer')),
                ('job_title', models.CharField(blank=True, help_text='Functietitel', max_length=100, verbose_name='functietitel')),
                ('department', models.CharField(blank=True, help_text='Afdeling', max_length=100, verbose_name='afdeling')),
                ('role', models.CharField(choices=[('decision_maker', 'Beslisser'), ('influencer', 'Beïnvloeder'), ('user', 'Gebruiker'), ('technical', 'Technisch contact'), ('financial', 'Financieel contact'), ('general', 'Algemeen contact')], default='general', help_text='Rol binnen het bedrijf', max_length=50, verbose_name='rol')),
                ('is_primary', models.BooleanField(default=False, help_text='Is dit de primaire contactpersoon?', verbose_name='primaire contactpersoon')),
                ('is_active', models.BooleanField(default=True, help_text='Is deze contactpersoon actief?', verbose_name='actief')),
                ('preferred_contact_method', models.CharField(choices=[('email', 'E-mail'), ('phone', 'Telefoon'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=20, verbose_name='voorkeur communicatiemethode')),
                ('language', models.CharField(choices=[('nl', 'Nederlands'), ('en', 'Engels'), ('de', 'Duits'), ('ar', 'Arabisch')], default='nl', max_length=10, verbose_name='taalvoorkeur')),
                ('notes', models.TextField(blank=True, help_text='Notities over deze contactpersoon', verbose_name='notities')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='aangemaakt op')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='bijgewerkt op')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client', verbose_name='klant')),
            ],
            options={
                'verbose_name': 'klantcontact',
                'verbose_name_plural': 'klantcontacten',
                'ordering': ['client', '-is_primary', 'last_name', 'first_name'],
                'unique_together': {('client', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('billing', 'Factuuradres'), ('shipping', 'Afleveradres'), ('office', 'Kantoor'), ('warehouse', 'Magazijn'), ('home', 'Thuisadres'), ('other', 'Overig')], default='billing', help_text='Type adres', max_length=20, verbose_name='adrestype')),
                ('street', models.CharField(help_text='Straatnaam en huisnummer', max_length=200, verbose_name='straat')),
                ('postal_code', models.CharField(help_text='Postcode', max_length=10, verbose_name='postcode')),
                ('city', models.CharField(help_text='Stad', max_length=100, verbose_name='stad')),
                ('state', models.CharField(blank=True, help_text='Provincie of staat', max_length=100, verbose_name='provincie/staat')),
                ('country', models.CharField(default='Nederland', help_text='Land', max_length=100, verbose_name='land')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geografische breedtegraad', max_digits=9, null=True, verbose_name='breedtegraad')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geografische lengtegraad', max_digits=9, null=True, verbose_name='lengtegraad')),
                ('is_primary', models.BooleanField(default=False, help_text='Is dit het primaire adres van dit type?', verbose_name='primair adres')),
                ('is_active', models.BooleanField(default=True, help_text='Is dit adres actief in gebruik?', verbose_name='actief')),
                ('phone', models.CharField(blank=True, help_text='Telefoonnummer voor dit adres', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Telefoonnummer moet in het formaat: '+31612345678'. Maximaal 15 cijfers.", regex='^\\+?1?\\d{9,15}$')], verbose_name='telefoonnummer')),
                ('instructions', models.TextField(blank=True, help_text='Speciale instructies voor dit adres', verbose_name='instructies')),
                ('notes', models.TextField(blank=True, help_text='Interne notities over dit adres', verbose_name='notities')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='aangemaakt op')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='bijgewerkt op')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='clients.client', verbose_name='klant')),
                ('contact_person', models.ForeignKey(blank=True, help_text='Contactpersoon op dit adres', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='clients.clientcontact', verbose_name='contactpersoon')),
            ],
            options={
                'verbose_name': 'adres',
                'verbose_name_plural': 'adressen',
                'ordering': ['client', 'address_type', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unieke identificatie voor dit object', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Datum en tijd wanneer dit object aangemaakt is', verbose_name='aangemaakt op')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Datum en tijd wanneer dit object voor het laatst bijgewerkt is', verbose_name='bijgewerkt op')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicatie of dit object zacht verwijderd is', verbose_name='verwijderd')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Datum en tijd wanneer dit object zacht verwijderd is', null=True, verbose_name='verwijderd op')),
                ('version', models.PositiveIntegerField(default=1, help_text='Versienummer voor optimistic locking', verbose_name='versie')),
                ('title', models.CharField(help_text='Titel van de notitie', max_length=200, verbose_name='titel')),
                ('content', models.TextField(help_text='Inhoud van de notitie', verbose_name='inhoud')),
                ('note_type', models.CharField(choices=[('general', 'Algemeen'), ('meeting', 'Vergadering'), ('call', 'Telefoongesprek'), ('email', 'E-mail'), ('task', 'Taak'), ('issue', 'Probleem'), ('opportunity', 'Kans'), ('other', 'Overig')], default='general', max_length=50, verbose_name='notitie type')),
                ('privacy_level', models.CharField(choices=[('public', 'Publiek (alle medewerkers)'), ('team', 'Team (alleen toegewezen team)'), ('private', 'Privé (alleen auteur)'), ('confidential', 'Vertrouwelijk (management)')], default='team', max_length=20, verbose_name='privacy niveau')),
                ('is_pinned', models.BooleanField(default=False, help_text='Is deze notitie vastgezet bovenaan?', verbose_name='vastgezet')),
                ('due_date', models.DateTimeField(blank=True, help_text='Vervaldatum voor actie-items', null=True, verbose_name='vervaldatum')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='clients.client', verbose_name='klant')),
                ('created_by', models.ForeignKey(blank=True, help_text='Gebruiker die dit object aangemaakt heeft', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='aangemaakt door')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Gebruiker die dit object voor het laatst bijgewerkt heeft', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='bijgewerkt door')),
            ],
            options={
                'verbose_name': 'klantnotitie',
                'verbose_name_plural': 'klantnotities',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_number'], name='clients_cli_client__d84143_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company_name'], name='clients_cli_company_9dfa94_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='clients_cli_status_ce0d15_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_type', 'status'], name='clients_cli_client__948337_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['assigned_to', 'status'], name='clients_cli_assigne_3fdedd_idx'),
        ),
    ]
